# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8b9d6fde4254262ea2b7410b93d4fd5308abd70f96d07047c085257db087aa6c5a192c0f9a77fdcd1608f4700b48a274fd2f21d41127dfa4c4aad83f9b46fa

test:
  secret_key_base: e20c27dcff93bc5b9519ec23868ca80b761c9d442ba6210ce37ea6ee5007f9c9130f2e494ba23da28660573f86803aaa0c150c8ae59eb91dd4474400758512fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
